// <auto-generated />
using System;
using AppSupport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppSupport.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201215190552_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AppSupport.Data.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExecuted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Manifest");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.ManifestPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManifestPlaneId")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestPlaneId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("RankId");

                    b.HasIndex("TravelerId");

                    b.ToTable("ManifestPerson");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.ManifestPlane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<int>("PlaneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.HasIndex("PlaneId");

                    b.ToTable("ManifestPlane");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DodId")
                        .HasColumnType("int");

                    b.Property<int?>("ExecutiveId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutiveId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RankId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Plane");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Database")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("AdventureWorksLT2019");

                    b.Property<string>("EditorFont")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Cascadia Code");

                    b.Property<int>("EditorFontSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(14);

                    b.Property<int>("EditorTabSpacing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Server")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue(".\\DevSql");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Query");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Rank");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.TemplatePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("TemplatePlaneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TemplatePlaneId");

                    b.ToTable("TemplatePerson");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.TemplatePlane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PlaneId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaneId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplatePlane");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DefaultPageSize")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHr")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTech")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocketName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Manifest", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Organization", "Organization")
                        .WithMany("Manifests")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.ManifestPerson", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.ManifestPlane", "ManifestPlane")
                        .WithMany("ManifestPeople")
                        .HasForeignKey("ManifestPlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.Organization", "Organization")
                        .WithMany("ManifestPeople")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.Person", "Person")
                        .WithMany("ManifestPlanes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.Rank", "Rank")
                        .WithMany("ManifestPeople")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.Person", "Traveler")
                        .WithMany("Trips")
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManifestPlane");

                    b.Navigation("Organization");

                    b.Navigation("Person");

                    b.Navigation("Rank");

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.ManifestPlane", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Manifest", "Manifest")
                        .WithMany("ManifestPlanes")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.Plane", "Plane")
                        .WithMany("PlaneManifests")
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manifest");

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Person", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Person", "Executive")
                        .WithMany("Associates")
                        .HasForeignKey("ExecutiveId");

                    b.HasOne("AppSupport.Data.Entities.Organization", "Organization")
                        .WithMany("People")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.Rank", "Rank")
                        .WithMany("People")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Executive");

                    b.Navigation("Organization");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Plane", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Organization", "Organization")
                        .WithMany("Planes")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Rank", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Branch", "Branch")
                        .WithMany("Ranks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Template", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Organization", "Organization")
                        .WithMany("Templates")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.TemplatePerson", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Person", "Person")
                        .WithMany("TemplatePlanes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.TemplatePlane", "TemplatePlane")
                        .WithMany("TemplatePeople")
                        .HasForeignKey("TemplatePlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("TemplatePlane");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.TemplatePlane", b =>
                {
                    b.HasOne("AppSupport.Data.Entities.Plane", "Plane")
                        .WithMany("PlaneTemplates")
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppSupport.Data.Entities.Template", "Template")
                        .WithMany("TemplatePlanes")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plane");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Branch", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Manifest", b =>
                {
                    b.Navigation("ManifestPlanes");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.ManifestPlane", b =>
                {
                    b.Navigation("ManifestPeople");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Organization", b =>
                {
                    b.Navigation("ManifestPeople");

                    b.Navigation("Manifests");

                    b.Navigation("People");

                    b.Navigation("Planes");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Person", b =>
                {
                    b.Navigation("Associates");

                    b.Navigation("ManifestPlanes");

                    b.Navigation("TemplatePlanes");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Plane", b =>
                {
                    b.Navigation("PlaneManifests");

                    b.Navigation("PlaneTemplates");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Rank", b =>
                {
                    b.Navigation("ManifestPeople");

                    b.Navigation("People");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.Template", b =>
                {
                    b.Navigation("TemplatePlanes");
                });

            modelBuilder.Entity("AppSupport.Data.Entities.TemplatePlane", b =>
                {
                    b.Navigation("TemplatePeople");
                });
#pragma warning restore 612, 618
        }
    }
}
